import sys

EXPECTED_RUNTIME_ERRORS = (TypeError, ValueError, RuntimeError, AttributeError, IndexError, KeyError, OSError)


def _viewer_runtime_module(viewer):
    try:
        return sys.modules.get(viewer.__class__.__module__)
    except EXPECTED_RUNTIME_ERRORS:
        return None


def _bind_impl(viewer, export_name: str):
    module = _viewer_runtime_module(viewer)
    if module is None:
        raise RuntimeError("viewer runtime module unavailable")
    impl_name = f"_drop_viewer_item_mod_logic_impl_{export_name}"
    if hasattr(module, impl_name):
        return getattr(module, impl_name)
    source = _SOURCES[export_name]
    exec(source, module.__dict__, module.__dict__)
    return getattr(module, impl_name)


_SOURCES = {
    'format_attribute_name': 'def _drop_viewer_item_mod_logic_impl_format_attribute_name(viewer, attr_name: Any) -> str:\n    txt = viewer._ensure_text(attr_name).replace("_", " ").strip()\n    txt = re.sub(r"([a-z])([A-Z])", r"\\1 \\2", txt)\n    return txt',
    'render_mod_description_template': 'def _drop_viewer_item_mod_logic_impl_render_mod_description_template(\n    viewer,\n    description: str,\n    matched_modifiers: list[tuple[int, int, int]],\n    default_value: int = 0,\n    attribute_name: str = "",\n) -> list[str]:\n    def _resolve_attribute_name(attr_id: int) -> str:\n        try:\n            return viewer._format_attribute_name(getattr(Attribute(int(attr_id)), "name", ""))\n        except EXPECTED_RUNTIME_ERRORS:\n            return ""\n\n    return render_mod_description_template(\n        description=viewer._ensure_text(description),\n        matched_modifiers=list(matched_modifiers or []),\n        default_value=int(default_value),\n        attribute_name=viewer._ensure_text(attribute_name),\n        resolve_attribute_name_fn=_resolve_attribute_name,\n        format_attribute_name_fn=viewer._format_attribute_name,\n        unknown_attribute_template="Attribute {id}",\n    )',
    'match_mod_definition_against_raw': 'def _drop_viewer_item_mod_logic_impl_match_mod_definition_against_raw(viewer, definition_modifiers, raw_mods) -> list[tuple[int, int, int]]:\n    meaningful = []\n    for dm in list(definition_modifiers or []):\n        mode = viewer._ensure_text(getattr(dm, "modifier_value_arg", "")).lower()\n        if "none" in mode:\n            continue\n        meaningful.append(dm)\n    if not meaningful:\n        return []\n\n    matched = []\n    for dm in meaningful:\n        ident = int(getattr(dm, "identifier", 0))\n        arg1 = int(getattr(dm, "arg1", 0))\n        arg2 = int(getattr(dm, "arg2", 0))\n        min_v = int(getattr(dm, "min", 0))\n        max_v = int(getattr(dm, "max", 0))\n        mode = viewer._ensure_text(getattr(dm, "modifier_value_arg", "")).lower()\n        found = None\n        for rid, ra1, ra2 in raw_mods:\n            if int(rid) != ident:\n                continue\n            if "arg1" in mode:\n                if int(ra2) == arg2 and min_v <= int(ra1) <= max_v:\n                    found = (int(rid), int(ra1), int(ra2))\n                    break\n            elif "arg2" in mode:\n                if int(ra1) == arg1 and min_v <= int(ra2) <= max_v:\n                    found = (int(rid), int(ra1), int(ra2))\n                    break\n            elif "fixed" in mode:\n                if int(ra1) == arg1 and int(ra2) == arg2:\n                    found = (int(rid), int(ra1), int(ra2))\n                    break\n        if found is None:\n            return []\n        matched.append(found)\n    return matched',
    'weapon_mod_type_matches': 'def _drop_viewer_item_mod_logic_impl_weapon_mod_type_matches(viewer, weapon_mod, item_type) -> bool:\n    if item_type is None or is_matching_item_type is None:\n        return False\n    try:\n        target_types = list(getattr(weapon_mod, "target_types", []) or [])\n        for target in target_types:\n            try:\n                if is_matching_item_type(item_type, target):\n                    return True\n            except EXPECTED_RUNTIME_ERRORS:\n                continue\n        item_mods = getattr(weapon_mod, "item_mods", {}) or {}\n        for target in list(item_mods.keys()):\n            try:\n                if is_matching_item_type(item_type, target):\n                    return True\n            except EXPECTED_RUNTIME_ERRORS:\n                continue\n    except EXPECTED_RUNTIME_ERRORS:\n        return False\n    return False',
    'collect_fallback_mod_lines': 'def _drop_viewer_item_mod_logic_impl_collect_fallback_mod_lines(viewer, raw_mods, item_attr_txt: str, item_type=None) -> list[str]:\n    lines = []\n    if viewer.mod_db is None:\n        return lines\n    best_by_ident = {}\n    try:\n        for weapon_mod in list(getattr(viewer.mod_db, "weapon_mods", {}).values()):\n            matched = viewer._match_mod_definition_against_raw(getattr(weapon_mod, "modifiers", []), raw_mods)\n            if not matched:\n                continue\n            ident_set = {int(m[0]) for m in matched}\n            if not ident_set:\n                continue\n            desc = viewer._ensure_text(getattr(weapon_mod, "description", "")).strip()\n            rendered = viewer._render_mod_description_template(desc, matched, 0, item_attr_txt)\n            if rendered:\n                first_line = rendered[0]\n                lower_desc = desc.lower()\n                has_old_school = "[old school]" in lower_desc\n                type_match = viewer._weapon_mod_type_matches(weapon_mod, item_type)\n                # Ranking:\n                # - direct type match is strongest signal,\n                # - old-school descriptors are allowed cross-type fallback,\n                # - plain cross-type matches are heavily penalized.\n                score = 0\n                if type_match:\n                    score += 100\n                if has_old_school:\n                    score += 20\n                if not type_match and not has_old_school:\n                    score -= 60\n                score += min(len(matched), 3)\n                for ident in ident_set:\n                    prev = best_by_ident.get(ident, None)\n                    if prev is None or score > int(prev.get("score", -999)):\n                        best_by_ident[ident] = {"line": first_line, "score": score}\n    except EXPECTED_RUNTIME_ERRORS:\n        return lines\n    for ident in sorted(best_by_ident.keys()):\n        line = viewer._ensure_text(best_by_ident[ident].get("line", "")).strip()\n        if line:\n            lines.append(line)\n    return lines',
    'collect_fallback_rune_lines': 'def _drop_viewer_item_mod_logic_impl_collect_fallback_rune_lines(viewer, raw_mods, item_attr_txt: str) -> list[str]:\n    lines = []\n    if viewer.mod_db is None:\n        return lines\n    best_by_ident = {}\n    try:\n        for rune in list(getattr(viewer.mod_db, "runes", {}).values()):\n            matched = viewer._match_mod_definition_against_raw(getattr(rune, "modifiers", []), raw_mods)\n            if not matched:\n                continue\n            ident_set = {int(m[0]) for m in matched}\n            if not ident_set:\n                continue\n            desc = viewer._ensure_text(getattr(rune, "description", "")).strip()\n            rune_name = viewer._ensure_text(getattr(rune, "name", "")).strip()\n            rendered = viewer._render_mod_description_template(desc, matched, 0, item_attr_txt)\n            candidate_lines = []\n            if rune_name:\n                candidate_lines.append(rune_name)\n            candidate_lines.extend(rendered)\n            if not candidate_lines and rune_name:\n                candidate_lines = [rune_name]\n            deduped_candidates = []\n            seen_line_keys = set()\n            for candidate in candidate_lines:\n                candidate_txt = viewer._ensure_text(candidate).strip()\n                if not candidate_txt:\n                    continue\n                line_key = re.sub(r"[^a-z0-9]+", "", candidate_txt.lower())\n                if line_key in seen_line_keys:\n                    continue\n                seen_line_keys.add(line_key)\n                deduped_candidates.append(candidate_txt)\n            candidate_lines = deduped_candidates\n            if not candidate_lines:\n                continue\n            score = min(len(matched), 4)\n            for ident in ident_set:\n                prev = best_by_ident.get(ident, None)\n                if prev is None or score > int(prev.get("score", -999)):\n                    best_by_ident[ident] = {"lines": list(candidate_lines), "score": score}\n    except EXPECTED_RUNTIME_ERRORS:\n        return lines\n    for ident in sorted(best_by_ident.keys()):\n        for line in list(best_by_ident[ident].get("lines", []) or []):\n            txt = viewer._ensure_text(line).strip()\n            if txt:\n                lines.append(txt)\n    return lines',
    'build_known_spellcast_mod_lines': 'def _drop_viewer_item_mod_logic_impl_build_known_spellcast_mod_lines(viewer, raw_mods, item_attr_txt: str, item_type=None) -> list[str]:\n    def _resolve_attribute_name(attr_id: int) -> str:\n        try:\n            return viewer._format_attribute_name(getattr(Attribute(int(attr_id)), "name", ""))\n        except EXPECTED_RUNTIME_ERRORS:\n            return ""\n    return build_known_spellcasting_mod_lines(\n        raw_mods,\n        item_attr_txt=viewer._ensure_text(item_attr_txt),\n        item_type=item_type,\n        resolve_attribute_name_fn=_resolve_attribute_name,\n        include_raw_when_no_chance=False,\n        use_range_chance=True,\n    )',
    'normalize_item_name': 'def _drop_viewer_item_mod_logic_impl_normalize_item_name(viewer, name: Any) -> str:\n    return viewer._clean_item_name(name).lower()',
    'extract_mod_lines_from_item_name': 'def _drop_viewer_item_mod_logic_impl_extract_mod_lines_from_item_name(viewer, item_name: Any) -> list[str]:\n    name_text = viewer._clean_item_name(item_name)\n    if "|" not in name_text:\n        return []\n    parts = [viewer._ensure_text(part).strip() for part in name_text.split("|")]\n    if len(parts) <= 1:\n        return []\n    lines = []\n    seen = set()\n    for part in parts[1:]:\n        if not part:\n            continue\n        key = re.sub(r"[^a-z0-9]+", "", part.lower())\n        if not key or key in seen:\n            continue\n        seen.add(key)\n        lines.append(part)\n    return lines',
    'extract_parsed_mod_name_parts': 'def _drop_viewer_item_mod_logic_impl_extract_parsed_mod_name_parts(viewer, parsed_result) -> tuple[str, str, str]:\n    prefix = ""\n    suffix = ""\n    inherent = ""\n    try:\n        parsed_prefix = getattr(parsed_result, "prefix", None)\n        if parsed_prefix is not None:\n            prefix = viewer._ensure_text(\n                getattr(getattr(parsed_prefix, "weapon_mod", None), "name", "")\n                or getattr(getattr(parsed_prefix, "rune", None), "name", "")\n            ).strip()\n        parsed_suffix = getattr(parsed_result, "suffix", None)\n        if parsed_suffix is not None:\n            suffix = viewer._ensure_text(\n                getattr(getattr(parsed_suffix, "weapon_mod", None), "name", "")\n                or getattr(getattr(parsed_suffix, "rune", None), "name", "")\n            ).strip()\n        parsed_inherent = getattr(parsed_result, "inherent", None)\n        if parsed_inherent is not None:\n            inherent = viewer._ensure_text(\n                getattr(getattr(parsed_inherent, "weapon_mod", None), "name", "")\n                or getattr(getattr(parsed_inherent, "rune", None), "name", "")\n            ).strip()\n    except EXPECTED_RUNTIME_ERRORS:\n        return "", "", ""\n    return prefix, suffix, inherent',
    'build_identified_name_from_modifiers': 'def _drop_viewer_item_mod_logic_impl_build_identified_name_from_modifiers(\n    viewer,\n    base_name: Any,\n    raw_mods: list[tuple[int, int, int]],\n    item_type_int: int,\n    model_id: int,\n) -> str:\n    clean_base = re.sub(r"^[\\d,]+\\s+", "", viewer._clean_item_name(base_name)).strip()\n    if not clean_base or not raw_mods or viewer.mod_db is None or parse_modifiers is None or ItemType is None:\n        return ""\n    try:\n        item_type = ItemType(int(item_type_int))\n    except EXPECTED_RUNTIME_ERRORS:\n        return ""\n    try:\n        parsed = parse_modifiers(list(raw_mods), item_type, int(model_id or 0), viewer.mod_db)\n    except EXPECTED_RUNTIME_ERRORS:\n        return ""\n    prefix, suffix, inherent = viewer._extract_parsed_mod_name_parts(parsed)\n    lower_base = clean_base.lower()\n    parts = []\n    changed = False\n    if prefix and prefix.lower() not in lower_base:\n        parts.append(prefix)\n        changed = True\n    parts.append(clean_base)\n    if suffix and suffix.lower() not in lower_base:\n        parts.append(suffix)\n        changed = True\n    elif inherent and inherent.lower() not in lower_base and not suffix:\n        parts.append(f"({inherent})")\n        changed = True\n    candidate = " ".join(viewer._ensure_text(part).strip() for part in parts if viewer._ensure_text(part).strip()).strip()\n    if not changed or not candidate or candidate.lower() == lower_base:\n        return ""\n    return candidate',
    'canonical_agg_item_name': 'def _drop_viewer_item_mod_logic_impl_canonical_agg_item_name(viewer, item_name: Any, rarity: Any, agg: dict) -> str:\n    name = viewer._clean_item_name(item_name)\n    if not name:\n        return "Unknown Item"\n    if name == "Gold":\n        return "Gold"\n\n    rarity_text = viewer._ensure_text(rarity).strip() or "Unknown"\n    lower_name = name.lower()\n    singular = lower_name[:-1] if lower_name.endswith("s") and len(lower_name) > 1 else lower_name\n    plural = singular + "s"\n\n    for (existing_name, existing_rarity) in agg.keys():\n        if viewer._ensure_text(existing_rarity).strip() != rarity_text:\n            continue\n        ex_lower = viewer._clean_item_name(existing_name).lower()\n        if ex_lower == lower_name:\n            return existing_name\n        # Conservative singular/plural normalization for same-rarity rows.\n        if ex_lower == singular or ex_lower == plural:\n            return existing_name\n    return name',
    'normalize_rarity_label': 'def _drop_viewer_item_mod_logic_impl_normalize_rarity_label(viewer, item_name: Any, rarity: Any) -> str:\n    name = viewer._clean_item_name(item_name)\n    r = viewer._ensure_text(rarity).strip() or "Unknown"\n    # Canonical buckets override color rarities.\n    if "Key" in name:\n        return "Keys"\n    if "Vial of Dye" in name or "Dye" in name:\n        return "Dyes"\n    if "Tome" in name:\n        return "Tomes"\n    return r',
}


def format_attribute_name(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'format_attribute_name')(viewer, *args, **kwargs)

def render_mod_description_template(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'render_mod_description_template')(viewer, *args, **kwargs)

def match_mod_definition_against_raw(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'match_mod_definition_against_raw')(viewer, *args, **kwargs)

def weapon_mod_type_matches(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'weapon_mod_type_matches')(viewer, *args, **kwargs)


def render_mod_description_template_local(viewer, *args, **kwargs):
    return render_mod_description_template(viewer, *args, **kwargs)

def collect_fallback_mod_lines(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'collect_fallback_mod_lines')(viewer, *args, **kwargs)

def collect_fallback_rune_lines(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'collect_fallback_rune_lines')(viewer, *args, **kwargs)

def build_known_spellcast_mod_lines(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'build_known_spellcast_mod_lines')(viewer, *args, **kwargs)

def normalize_item_name(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'normalize_item_name')(viewer, *args, **kwargs)

def extract_mod_lines_from_item_name(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'extract_mod_lines_from_item_name')(viewer, *args, **kwargs)

def extract_parsed_mod_name_parts(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'extract_parsed_mod_name_parts')(viewer, *args, **kwargs)

def build_identified_name_from_modifiers(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'build_identified_name_from_modifiers')(viewer, *args, **kwargs)

def canonical_agg_item_name(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'canonical_agg_item_name')(viewer, *args, **kwargs)

def normalize_rarity_label(viewer, *args, **kwargs):
    return _bind_impl(viewer, 'normalize_rarity_label')(viewer, *args, **kwargs)
